version: '3.9'
services:
  eureka-server:
    image: dimmaryanto93/com.maryanto.dimas.spring-cloudnative:eureka-v1
    build:
      dockerfile: Dockerfile
      context: ./eureka-server
      args:
        JAR_FILE: eureka-server-1.0.0-release.jar
    ports:
      - "8761:8761"
  api-wilayah:
    image: dimmaryanto93/com.maryanto.dimas.spring-cloudnative:api-wilayah-v1
    build:
      dockerfile: Dockerfile
      context: ./api-wilayah
      args:
        JAR_FILE: api-wilayah-1.0.0-release.jar
    ports:
      - "9091:8080"
    env_file:
      - springboot.env
  api-nasabah:
    image: dimmaryanto93/com.maryanto.dimas.spring-cloudnative:api-nasabah-v1
    build:
      dockerfile: Dockerfile
      context: ./api-nasabah
      args:
        JAR_FILE: api-nasabah-1.0.0-release.jar
    ports:
      - "9092:8080"
    env_file:
      - springboot.env