POST {{host}}:{{port-uploader}}{{context-path}}/api/v1/minio/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="honda-cbr1000rr.jpg"
Content-Type: application/octet-stream

< ./honda-cbr1000rr.jpg

--WebAppBoundary
Content-Disposition: form-data; name="folder";
Content-Type: application/x-www-form-urlencoded

images/profile

### upload file

POST {{host}}:{{port-uploader}}{{context-path}}/api/v1/minio/preview
Content-Type: application/json

{
  "objectId": "images/profile/8dc0f240-d1d1-450a-a5f3-c1d813b87f58.jpg",
  "duration": 1,
  "unit": "HOURS"
}

### presigned url from object id

POST {{host}}:{{port-uploader}}{{context-path}}/api/v1/minio/download
Content-Type: application/json

{
  "objectId": "images/profile/b9b03505-6dbc-4580-aa26-e2e6912c948a.jpg"
}

### dowload file as stream/octet
