### GET list kota
GET {{host}}:{{port-wilayah}}{{context-path}}/api/kota/list
Host: api-wilayah.wahidin.go.id
Content-Type: application/json

### Get find by id
GET {{host}}:{{port-wilayah}}{{context-path}}/api/kota/findById/02
Host: api-wilayah.wahidin.go.id
Content-Type: application/json