### GET list kota
GET 10.12.11.12/api/kota/list
Host: api-wilayah.wahidin.go.id
Content-Type: application/json

### Get find by id
GET 10.12.11.12/api/kota/findById/02
Host: api-wilayah.wahidin.go.id
Content-Type: application/json