eureka:
  instance:
    hostname: ${HOSTNAME:localhost}

  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    enabled: ${EUREKA_ENABLE:false}
    fetch-registry: true
    healthcheck:
      enabled: true

spring:
  application:
    name: api-wilayah

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
  otlp:
    tracing:
      endpoint: http://${OLTP_HOST:localhost}:${OLTP_PORT:4318}/v1/metrics
  wavefront:
    application:
      service-name: ${spring.application.name}

server:
  port: ${APPLICATION_PORT:9091}