apiVersion: v1
kind: Service
metadata:
  name: api-nasabah
spec:
  selector:
    app: api-nasabah
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32437
  type: NodePort