### Post request to create new nasabah
POST {{host}}:{{port-nasabah}}{{context-path}}/api/nasabah/register
Host: api-nasabah.wahidin.go.id
Content-Type: application/json

{
  "nik": "62xxxxx",
  "namaLengkap": "Dimas Maryanto",
  "alamat": "Jl. Bukit Indah no B8 kab.Bandung",
  "idKota": "02"
}