eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    enabled: ${EUREKA_ENABLE:false}
    fetch-registry: true
    healthcheck:
      enabled: true

spring:
  application:
    name: api-nasabah

tracing:
  url: http://${JAEGER_TELEMETRY_HOST:localhost}:${JAEGER_TELEMETRY_PORT:4318}/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${APPLICATION_PORT:9092}

clients:
  wilayah-service:
    url: http://${SERVICE_WILAYAH_HOST:localhost}:${SERVICE_WILAYAH_PORT:9091}

otel:
  exporter:
    jaeger:
      enabled: true
    otlp:
      enabled: true
      endpoint: http://${OLTP_HOST:localhost}:${OLTP_PORT:4317}
  propagation:
    type: tracecontext,baggage